/**
 * The desktop window's markup.
 *
 * One self-contained string: no bundler step, no asset paths, no network. The
 * page is served once from loopback and never fetches anything external, so
 * there is nothing here for a CDN or an ad blocker to interfere with, and no
 * third party learns that the miner is running.
 *
 * The nonce is interpolated into a JS string literal. It is generated by
 * `randomBytes(...).toString("base64url")`, so it is [A-Za-z0-9_-] only and
 * cannot terminate the literal -- but the assertion is enforced here rather
 * than assumed, because "the caller always passes something safe" is how
 * injection bugs are written.
 */

const SAFE_NONCE = /^[A-Za-z0-9_-]+$/;

export function renderApp(nonce: string): string {
  if (!SAFE_NONCE.test(nonce)) throw new Error("renderApp: unsafe nonce");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'">
<title>USAGE Miner</title>
<style>
  :root {
    color-scheme: light dark;
    --bg: #fbfbfa; --surface: #ffffff; --border: #e6e4df; --text: #17150f;
    --muted: #6b665c; --verified: #1f7a4d; --routed: #2563a8; --reported: #8b8578;
    --danger: #a33; --accent: #17150f; --accent-text: #fbfbfa;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #131210; --surface: #1b1a17; --border: #2e2c27; --text: #efece5;
      --muted: #9a948a; --verified: #4ec38a; --routed: #6aa6e8; --reported: #8b8578;
      --accent: #efece5; --accent-text: #131210;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--bg); color: var(--text);
    font: 14px/1.5 ui-sans-serif, system-ui, "Segoe UI", sans-serif;
  }
  .wrap { max-width: 620px; margin: 0 auto; padding: 32px 20px 56px; }
  h1 { font-size: 22px; font-weight: 500; letter-spacing: -0.01em; margin: 0; }
  .sub { color: var(--muted); font-size: 12px; margin-top: 4px; }
  .card {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 6px; padding: 16px; margin-top: 12px;
  }
  .card h2 {
    font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em;
    color: var(--muted); font-weight: 500; margin: 0 0 10px;
  }
  .row { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 8px 0; }
  .row + .row { border-top: 1px solid var(--border); }
  .name { font-weight: 500; }
  .meta { color: var(--muted); font-size: 12px; }
  button {
    font: inherit; font-size: 13px; padding: 6px 14px; border-radius: 5px;
    border: 1px solid var(--border); background: var(--surface); color: var(--text);
    cursor: pointer;
  }
  button:hover:not(:disabled) { border-color: var(--muted); }
  button:disabled { opacity: 0.45; cursor: default; }
  button.primary { background: var(--accent); color: var(--accent-text); border-color: var(--accent); }
  .tag { font-size: 11px; padding: 2px 7px; border-radius: 999px; border: 1px solid currentColor; }
  .tag.on { color: var(--verified); }
  .tag.off { color: var(--reported); }
  .tag.warn { color: var(--routed); }
  .code {
    font: 600 28px/1 ui-monospace, "Cascadia Mono", Consolas, monospace;
    letter-spacing: 0.22em; padding: 14px 0 6px;
  }
  .note { color: var(--muted); font-size: 12px; margin-top: 10px; }
  .err { color: var(--danger); font-size: 12px; margin-top: 10px; }
  .links { margin-top: 20px; display: flex; gap: 16px; flex-wrap: wrap; }
  .links button { border: 0; background: none; padding: 0; color: var(--routed); font-size: 12px; }
  .empty { color: var(--muted); font-size: 12px; }
  .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; }
  .cell { padding: 10px; border: 1px solid var(--border); border-radius: 5px; }
  .cell-label { font-size: 11px; color: var(--muted); }
  .cell-value { font-size: 18px; font-weight: 500; margin-top: 2px; font-variant-numeric: tabular-nums; }
  .cell-hint { font-size: 10px; color: var(--muted); margin-top: 2px; }
  .feed { margin-top: 10px; border-top: 1px solid var(--border); }
  .actions { display: flex; align-items: center; gap: 12px; }
  .switch { display: flex; align-items: center; gap: 6px; font-size: 12px; cursor: pointer; }
  .priv { padding: 8px 0; border-top: 1px solid var(--border); }
  .priv:first-of-type { border-top: 0; }
</style>
</head>
<body>
<div class="wrap" id="app"><p class="empty">Loading…</p></div>
<script>
(function () {
  "use strict";
  var K = "${nonce}";
  var app = document.getElementById("app");
  var busy = false;

  // Every request is bounded, and a non-JSON answer is an error rather than
  // a hang: the window must never wait on the local process forever.
  var REQUEST_TIMEOUT_MS = 20000;
  function api(path, body) {
    var controller = typeof AbortController === "function" ? new AbortController() : null;
    var timer = controller ? setTimeout(function () { controller.abort(); }, REQUEST_TIMEOUT_MS) : null;
    return fetch(path + "?k=" + K, {
      method: body === undefined ? "GET" : "POST",
      headers: { "content-type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body),
      signal: controller ? controller.signal : undefined
    }).then(function (r) {
      return r.text().then(function (text) {
        try { return JSON.parse(text); } catch (e) { throw new Error("bad_json"); }
      });
    }).finally(function () { if (timer) clearTimeout(timer); });
  }

  // What the user sees instead of "Loading…" when startup fails. The
  // category is a word, never a message that could carry a path, a token or
  // a header; the log in %APPDATA%\\USAGE has the detail.
  var rendered = false;
  function renderFailure(category) {
    app.textContent = "";
    var head = el("div");
    head.appendChild(el("h1", null, "USAGE Miner"));
    app.appendChild(head);
    var card = el("div", "card");
    card.appendChild(el("h2", null, "Something went wrong while starting."));
    card.appendChild(el("div", "note",
      "USAGE Miner is running, but this window could not load its state. Retry, or close this tab and open USAGE Miner again."));
    var retry = el("button", "primary", "Retry");
    retry.style.marginTop = "12px";
    retry.onclick = function () { app.textContent = ""; app.appendChild(el("p", "empty", "Loading…")); refresh(); };
    card.appendChild(retry);
    card.appendChild(el("div", "meta", "Technical details: " + category));
    app.appendChild(card);
  }
  function categorize(error) {
    var m = error && error.message ? String(error.message) : "";
    if (error && error.name === "AbortError") return "timeout";
    if (m === "bad_json") return "bad_response";
    if (/fetch|network|Failed/i.test(m)) return "unreachable";
    return "render";
  }

  // Everything shown comes from the local process, but it is still built with
  // textContent rather than innerHTML: a provider label or a device name is
  // data, and data never becomes markup.
  function el(tag, cls, text) {
    var node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text !== undefined && text !== null) node.textContent = String(text);
    return node;
  }

  function act(fn) {
    if (busy) return;
    busy = true;
    fn().catch(function () {}).then(function () { busy = false; refresh(); });
  }

  function render(state) {
    app.textContent = "";

    var head = el("div");
    head.appendChild(el("h1", null, "USAGE Miner"));
    head.appendChild(el("div", "sub", "Version " + state.version +
      (state.deviceName ? " · " + state.deviceName : "")));
    app.appendChild(head);

    if (state.pairing) {
      var pair = el("div", "card");
      pair.appendChild(el("h2", null, "Approve this device"));
      pair.appendChild(el("div", "code", state.pairing.userCode));
      pair.appendChild(el("div", "note",
        "Your browser is open at " + state.pairing.verificationUrl.split("?")[0] +
        ". Approve the device there — this window finishes on its own."));
      app.appendChild(pair);
      return;
    }

    if (!state.signedIn) {
      var signIn = el("div", "card");
      signIn.appendChild(el("h2", null, "Get started"));
      signIn.appendChild(el("div", "note",
        "Sign in through your browser. Nothing to copy, and no key to paste."));
      var b = el("button", "primary", "Sign in");
      b.style.marginTop = "12px";
      b.onclick = function () { act(function () { return api("/sign-in", {}); }); };
      signIn.appendChild(b);
      if (state.error) signIn.appendChild(el("div", "err", state.error));
      app.appendChild(signIn);
      appendFooter(state);
      return;
    }

    var acct = el("div", "card");
    acct.appendChild(el("h2", null, "Account"));
    var acctRow = el("div", "row");
    acctRow.appendChild(el("div", "name", state.accountLabel || "Signed in"));
    acctRow.appendChild(el("span", "meta", state.network || ""));
    acct.appendChild(acctRow);
    if (state.offline) {
      acct.appendChild(el("div", "err", "Offline — unable to reach USAGE. Local detection still works; usage uploads resume when the connection returns."));
      var again = el("button", "primary", "Retry");
      again.style.marginTop = "8px";
      again.onclick = function () { refresh(); };
      acct.appendChild(again);
    } else if (state.error) acct.appendChild(el("div", "err", state.error));
    if (state.updateAvailable) {
      acct.appendChild(el("div", "note", "A newer USAGE Miner is available."));
    }
    if (state.securityNotice) {
      acct.appendChild(el("div", "note", "Security update: " + state.securityNotice));
    }
    app.appendChild(acct);

    var prov = el("div", "card");
    prov.appendChild(el("h2", null, "Providers"));
    if (!state.providers.length) {
      prov.appendChild(el("div", "empty", "No AI provider connected yet."));
      var connect = el("button", "primary", "Connect a provider");
      connect.style.marginTop = "12px";
      connect.onclick = function () { act(function () { return api("/open", { target: "providers" }); }); };
      prov.appendChild(connect);
    } else {
      state.providers.forEach(function (p) {
        var row = el("div", "row");
        row.appendChild(el("div", "name", p.label));
        row.appendChild(el("span", "meta", p.miningLabel));
        prov.appendChild(row);
      });
    }
    app.appendChild(prov);

    // ------------------------------------------------------------ TODAY
    // Three numbers that must never be one number. Tracked is what this
    // machine saw; verified is what USAGE could corroborate; eligible is what
    // the reward policy admitted. Each is a subset of the one before it.
    var today = el("div", "card");
    today.appendChild(el("h2", null, "Today"));
    if (state.usage) {
      var grid = el("div", "grid");
      [
        ["Tracked AI usage", fmtTokens(state.usage.trackedTokens) + " tokens", "what your tools reported"],
        ["Verified AI usage", fmtTokens(state.usage.verifiedTokens) + " tokens", "confirmed by USAGE"],
        ["Mining eligible", fmtMicros(state.usage.eligibleComputeMicros), "compute that can earn"],
        ["Estimated USAGE", state.usage.estimatedPoints ? "+" + state.usage.estimatedPoints : "—", "until the epoch settles"]
      ].forEach(function (cell) {
        var c = el("div", "cell");
        c.appendChild(el("div", "cell-label", cell[0]));
        c.appendChild(el("div", "cell-value tnum", cell[1]));
        c.appendChild(el("div", "cell-hint", cell[2]));
        grid.appendChild(c);
      });
      today.appendChild(grid);
      if (state.usage.recent && state.usage.recent.length) {
        var feed = el("div", "feed");
        state.usage.recent.slice(0, 6).forEach(function (r) {
          var line = el("div", "row");
          line.appendChild(el("span", "meta", toolName(state, r.tool) + " · " + fmtTokens(r.tokens) + " tokens"));
          line.appendChild(el("span", "tag " + (r.status === "tracked" ? "off" : "on"),
            r.status === "tracked" ? "TRACKED" : r.status === "routed" ? "ROUTED ✓" : "VERIFIED ✓"));
          feed.appendChild(line);
        });
        today.appendChild(feed);
      }
    } else {
      today.appendChild(el("div", "empty", "Figures appear once USAGE has seen usage from this device."));
    }
    app.appendChild(today);

    // --------------------------------------------------------- AI TOOLS
    var tools = el("div", "card");
    tools.appendChild(el("h2", null, "AI apps found on this computer"));
    state.tools.forEach(function (t) {
      var row = el("div", "row");
      var left = el("div");
      left.appendChild(el("div", "name", t.name + (t.experimental ? "  (experimental)" : "")));
      var status;
      if (t.detectionUnavailable) status = "Detection unavailable";
      else if (!t.installed) status = "Not detected";
      else if (!t.meterable) status = t.availabilityNote || "Cannot be metered here";
      else if (t.mapped) status = "Usage mapping ON · verification up to: " + ceilingLabel(t.verificationCeiling);
      else status = "Detected" + (t.version ? " · " + t.version : "") + " · mapping off";
      left.appendChild(el("div", "meta", status));
      if (t.conflict) left.appendChild(el("div", "meta", t.conflict));
      row.appendChild(left);

      var right = el("div", "actions");
      if (t.installed && t.meterable) {
        var label = el("label", "switch");
        var box = document.createElement("input");
        box.type = "checkbox";
        box.checked = t.mapped;
        box.onchange = function () {
          var enable = box.checked;
          if (enable && !window.confirm(
            "Allow USAGE to meter " + t.name + "?\\n\\nUSAGE reads: " + t.reads.join(", ") +
            ".\\nUSAGE never reads: " + t.neverReads.join(", ") + "."
          )) { box.checked = false; return; }
          act(function () {
            return api("/mapping", { tool: t.id, enabled: enable }).then(function (r) {
              if (r && r.error) window.alert(r.message || "Could not change mapping.");
            });
          });
        };
        label.appendChild(box);
        label.appendChild(el("span", null, "Map usage"));
        right.appendChild(label);

        if (t.mode === "launch" || t.id === "codex") {
          var start = el("button", "primary", "Start with USAGE");
          start.onclick = function () {
            act(function () {
              return api("/launch", { tool: t.id }).then(function (r) {
                if (r && r.error) window.alert(r.message || "Could not start it.");
              });
            });
          };
          right.appendChild(start);
        }
      } else if (!t.installed) {
        right.appendChild(el("span", "tag off", "—"));
      }
      row.appendChild(right);
      tools.appendChild(row);
    });
    tools.appendChild(el("div", "note",
      "Mapping is per app and opt-in. A mapped app is metered from its own official telemetry when USAGE starts it; " +
      "nothing is written to the app's settings and nothing is read from your files. " +
      "Tracked usage appears here and on your web account; only usage USAGE can verify itself can earn."));
    app.appendChild(tools);

    // ------------------------------------------------------------ PRIVACY
    var privacy = el("div", "card");
    privacy.appendChild(el("h2", null, "Exactly what USAGE reads"));
    state.tools.filter(function (t) { return t.installed && t.meterable; }).forEach(function (t) {
      var block = el("div", "priv");
      block.appendChild(el("div", "name", t.name));
      block.appendChild(el("div", "meta", "Reads: " + (t.reads.length ? t.reads.join(" · ") : "nothing")));
      block.appendChild(el("div", "meta", "Never reads: " + t.neverReads.join(" · ")));
      privacy.appendChild(block);
    });
    privacy.appendChild(el("div", "note",
      "USAGE measures compute metadata, not conversations. No prompt, response, file, command or line of code leaves this computer through USAGE Miner — the parser has no field to put one in."));
    app.appendChild(privacy);

    appendFooter(state);
  }

  function fmtTokens(n) {
    n = Number(n || 0);
    if (n >= 1e6) return (n / 1e6).toFixed(n >= 1e7 ? 0 : 1) + "M";
    if (n >= 1e3) return (n / 1e3).toFixed(n >= 1e4 ? 0 : 1) + "k";
    return String(n);
  }
  function fmtMicros(m) {
    m = Number(m || 0);
    return "$" + (m / 1e6).toFixed(m >= 1e6 ? 2 : 4) + " equiv.";
  }
  function toolName(state, id) {
    var t = state.tools.filter(function (x) { return x.id === id; })[0];
    return t ? t.name : id;
  }
  function ceilingLabel(c) {
    return c === "routed_confirmed" ? "routed" : c === "provider_correlated" ? "verified (when correlated)" : "tracked only";
  }

  function appendFooter(state) {
    var links = el("div", "links");
    if (state.signedIn) {
      var dash = el("button", null, "Open dashboard");
      dash.onclick = function () { act(function () { return api("/open", { target: "dashboard" }); }); };
      links.appendChild(dash);

      var devices = el("button", null, "Manage devices");
      devices.onclick = function () { act(function () { return api("/open", { target: "miners" }); }); };
      links.appendChild(devices);

      var so = el("button", null, "Sign out");
      so.onclick = function () {
        if (!window.confirm("Sign this device out? Mining stops until you sign in again.")) return;
        act(function () { return api("/sign-out", {}); });
      };
      links.appendChild(so);
    }
    var quit = el("button", null, "Quit");
    quit.onclick = function () {
      api("/quit", {});
      document.body.textContent = "You can close this tab.";
    };
    links.appendChild(quit);
    app.appendChild(links);
  }

  function refresh() {
    return api("/state").then(function (state) {
      if (!state || typeof state !== "object" || !Array.isArray(state.tools)) throw new Error("bad_json");
      render(state);
      rendered = true;
    }).catch(function (error) {
      if (rendered && categorize(error) === "unreachable") {
        app.textContent = "";
        app.appendChild(el("p", "err", "USAGE Miner is no longer running. You can close this tab."));
        return;
      }
      renderFailure(categorize(error));
    });
  }

  // Startup timeout: if nothing has rendered by now, something is wrong and
  // the user is told so. There is no state in which "Loading…" stays forever.
  var STARTUP_TIMEOUT_MS = 25000;
  setTimeout(function () { if (!rendered && app.textContent.indexOf("Loading") !== -1) renderFailure("startup_timeout"); }, STARTUP_TIMEOUT_MS);

  try { refresh(); } catch (error) { renderFailure("render"); }
  // Slow enough to be invisible, fast enough that an approval in the browser
  // lands in this window without the user doing anything.
  setInterval(function () { if (!busy) refresh(); }, 3000);
})();
</script>
</body>
</html>`;
}
