/**
 * The desktop window's markup.
 *
 * One self-contained string: no bundler step, no asset paths, no network. The
 * page is served once from loopback and never fetches anything external, so
 * there is nothing here for a CDN or an ad blocker to interfere with, and no
 * third party learns that the miner is running.
 *
 * The nonce is interpolated into a JS string literal. It is generated by
 * `randomBytes(...).toString("base64url")`, so it is [A-Za-z0-9_-] only and
 * cannot terminate the literal -- but the assertion is enforced here rather
 * than assumed, because "the caller always passes something safe" is how
 * injection bugs are written.
 */

const SAFE_NONCE = /^[A-Za-z0-9_-]+$/;

export function renderApp(nonce: string): string {
  if (!SAFE_NONCE.test(nonce)) throw new Error("renderApp: unsafe nonce");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'">
<title>USAGE Miner</title>
<style>
  :root {
    color-scheme: light dark;
    --bg: #fbfbfa; --surface: #ffffff; --border: #e6e4df; --text: #17150f;
    --muted: #6b665c; --verified: #1f7a4d; --routed: #2563a8; --reported: #8b8578;
    --danger: #a33; --accent: #17150f; --accent-text: #fbfbfa;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #131210; --surface: #1b1a17; --border: #2e2c27; --text: #efece5;
      --muted: #9a948a; --verified: #4ec38a; --routed: #6aa6e8; --reported: #8b8578;
      --accent: #efece5; --accent-text: #131210;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--bg); color: var(--text);
    font: 14px/1.5 ui-sans-serif, system-ui, "Segoe UI", sans-serif;
  }
  .setup { border:1px solid var(--line); border-radius:10px; padding:14px 16px; margin-bottom:12px; background:var(--card); }
  .setup h2 { margin:0 0 2px; }
  .setup .lead { color:var(--dim); font-size:12px; margin:0 0 12px; }
  .step { display:grid; grid-template-columns:22px 1fr auto; gap:10px; align-items:start; padding:10px 0; border-top:1px solid var(--line); }
  .step:first-of-type { border-top:0; }
  .step .mark { font:600 12px/20px ui-monospace, monospace; text-align:center; border-radius:50%; width:20px; height:20px; }
  .step .mark.done { color:var(--ok); }
  .step .mark.now { background:var(--fg); color:var(--card); }
  .step .mark.later { color:var(--dim); }
  .step .title { font-size:13px; }
  .step .why { color:var(--dim); font-size:12px; margin-top:2px; line-height:1.45; }
  .step.is-done .title, .step.is-done .why { color:var(--dim); }
  .step code { display:block; margin-top:6px; padding:6px 8px; border:1px solid var(--line); border-radius:4px; font-size:12px; overflow-x:auto; }

  .wrap { max-width: 620px; margin: 0 auto; padding: 32px 20px 56px; }
  h1 { font-size: 22px; font-weight: 500; letter-spacing: -0.01em; margin: 0; }
  .sub { color: var(--muted); font-size: 12px; margin-top: 4px; }
  .card {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 6px; padding: 16px; margin-top: 12px;
  }
  .card h2 {
    font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em;
    color: var(--muted); font-weight: 500; margin: 0 0 10px;
  }
  .row { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 8px 0; }
  .row + .row { border-top: 1px solid var(--border); }
  .name { font-weight: 500; }
  .meta { color: var(--muted); font-size: 12px; }
  button {
    font: inherit; font-size: 13px; padding: 6px 14px; border-radius: 5px;
    border: 1px solid var(--border); background: var(--surface); color: var(--text);
    cursor: pointer;
  }
  button:hover:not(:disabled) { border-color: var(--muted); }
  button:disabled { opacity: 0.45; cursor: default; }
  button.primary { background: var(--accent); color: var(--accent-text); border-color: var(--accent); }
  .tag { font-size: 11px; padding: 2px 7px; border-radius: 999px; border: 1px solid currentColor; }
  .tag.on { color: var(--verified); }
  .tag.off { color: var(--reported); }
  .tag.warn { color: var(--routed); }
  .code {
    font: 600 28px/1 ui-monospace, "Cascadia Mono", Consolas, monospace;
    letter-spacing: 0.22em; padding: 14px 0 6px;
  }
  .note { color: var(--muted); font-size: 12px; margin-top: 10px; }
  .err { color: var(--danger); font-size: 12px; margin-top: 10px; }
  .links { margin-top: 20px; display: flex; gap: 16px; flex-wrap: wrap; }
  .links button { border: 0; background: none; padding: 0; color: var(--routed); font-size: 12px; }
  .empty { color: var(--muted); font-size: 12px; }
  .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; }
  .cell { padding: 10px; border: 1px solid var(--border); border-radius: 5px; }
  .cell-label { font-size: 11px; color: var(--muted); }
  .cell-value { font-size: 18px; font-weight: 500; margin-top: 2px; font-variant-numeric: tabular-nums; }
  .cell-hint { font-size: 10px; color: var(--muted); margin-top: 2px; }
  .feed { margin-top: 10px; border-top: 1px solid var(--border); }
  .actions { display: flex; align-items: center; gap: 12px; }
  .switch { display: flex; align-items: center; gap: 6px; font-size: 12px; cursor: pointer; }
  .priv { padding: 8px 0; border-top: 1px solid var(--border); }
  .priv:first-of-type { border-top: 0; }
  .tool { padding: 12px 0; }
  .tool + .tool { border-top: 1px solid var(--border); }
  .tool > .row { padding: 0 0 6px; }
  .kv { display: grid; grid-template-columns: 128px 1fr; gap: 2px 12px; font-size: 12px; }
  .kv .k { color: var(--muted); }
  .kv .v { font-variant-numeric: tabular-nums; }
  .kv .v.dim { color: var(--muted); }
  .kv .v.bad { color: var(--danger); }
</style>
</head>
<body>
<div class="wrap" id="app"><p class="empty">Loading…</p></div>
<script>
(function () {
  "use strict";
  var K = "${nonce}";
  var app = document.getElementById("app");
  var busy = false;

  // Every request is bounded, and a non-JSON answer is an error rather than
  // a hang: the window must never wait on the local process forever.
  var REQUEST_TIMEOUT_MS = 20000;
  function api(path, body) {
    var controller = typeof AbortController === "function" ? new AbortController() : null;
    var timer = controller ? setTimeout(function () { controller.abort(); }, REQUEST_TIMEOUT_MS) : null;
    return fetch(path + "?k=" + K, {
      method: body === undefined ? "GET" : "POST",
      headers: { "content-type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body),
      signal: controller ? controller.signal : undefined
    }).then(function (r) {
      return r.text().then(function (text) {
        var body;
        try { body = JSON.parse(text); } catch (e) { throw new Error("bad_json"); }
        // A refusal is an answer, never a success: an error status always
        // carries an error code, whatever the body said.
        if (!r.ok && body && typeof body === "object" && !body.error) body.error = "http_" + r.status;
        if (body && typeof body === "object") body.httpStatus = r.status;
        return body;
      });
    }).finally(function () { if (timer) clearTimeout(timer); });
  }

  // The page re-renders every few seconds. A render between a button's
  // mousedown and mouseup replaces the button, and the click never fires --
  // so no render while a pointer is down.
  var pointerDown = false;
  document.addEventListener("pointerdown", function () { pointerDown = true; }, true);
  document.addEventListener("pointerup", function () { setTimeout(function () { pointerDown = false; }, 0); }, true);
  document.addEventListener("pointercancel", function () { pointerDown = false; }, true);

  // What the last "Measure everywhere" click did, kept across re-renders until
  // the next click: { kind: "ok" | "err", title, text, warning }.
  var aoNotice = null;

  // What the user sees instead of "Loading…" when startup fails. The
  // category is a word, never a message that could carry a path, a token or
  // a header; the log in %APPDATA%\\USAGE has the detail.
  var rendered = false;
  function renderFailure(category) {
    app.textContent = "";
    var head = el("div");
    head.appendChild(el("h1", null, "USAGE Miner"));
    app.appendChild(head);
    var card = el("div", "card");
    card.appendChild(el("h2", null, "Something went wrong while starting."));
    card.appendChild(el("div", "note",
      "USAGE Miner is running, but this window could not load its state. Retry, or close this tab and open USAGE Miner again."));
    var retry = el("button", "primary", "Retry");
    retry.style.marginTop = "12px";
    retry.onclick = function () { app.textContent = ""; app.appendChild(el("p", "empty", "Loading…")); refresh(); };
    card.appendChild(retry);
    card.appendChild(el("div", "meta", "Technical details: " + category));
    app.appendChild(card);
  }
  function categorize(error) {
    var m = error && error.message ? String(error.message) : "";
    if (error && error.name === "AbortError") return "timeout";
    if (m === "bad_json") return "bad_response";
    if (/fetch|network|Failed/i.test(m)) return "unreachable";
    return "render";
  }

  // Everything shown comes from the local process, but it is still built with
  // textContent rather than innerHTML: a provider label or a device name is
  // data, and data never becomes markup.
  function el(tag, cls, text) {
    var node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text !== undefined && text !== null) node.textContent = String(text);
    return node;
  }

  // A request that never got an answer is said out loud, not swallowed: the
  // user must be able to tell "it failed" from "it worked".
  function act(fn) {
    if (busy) return false;
    busy = true;
    fn().catch(function (error) {
      window.alert("USAGE Miner did not answer (" + categorize(error) + "). Nothing may have changed. If this keeps happening, close this tab and open USAGE Miner again.");
    }).then(function () { busy = false; refresh(); });
    return true;
  }

  function setupCard(state) {
    var card = el("div", "setup");
    card.appendChild(el("h2", null, "Three things, then you are mining"));
    card.appendChild(el("p", "lead", "USAGE needs all three. It cannot reward compute it did not carry, cannot price, or cannot prove was paid for."));

    state.setup.steps.forEach(function (step, index) {
      var row = el("div", "step" + (step.done ? " is-done" : ""));
      var state_ = step.done ? "done" : index === state.setup.nextIndex ? "now" : "later";
      row.appendChild(el("span", "mark " + state_, step.done ? "✓" : String(index + 1)));

      var mid = el("div");
      mid.appendChild(el("div", "title", step.title));
      mid.appendChild(el("div", "why", step.detail));
      if (step.action && step.action.kind === "command") {
        mid.appendChild(el("code", null, step.action.command));
      }
      row.appendChild(mid);

      var right = el("div", "actions");
      if (step.action && step.action.kind === "sign_in") {
        var signIn = el("button", "primary", step.action.label);
        signIn.onclick = function () { act(function () { return api("/sign-in", {}); }); };
        right.appendChild(signIn);
      } else if (step.action && step.action.kind === "open") {
        var open = el("button", "primary", step.action.label);
        open.onclick = function () {
          act(function () { return api("/open", { target: step.action.target }); });
        };
        right.appendChild(open);
      } else if (step.action && step.action.kind === "command") {
        var copy = el("button", null, step.action.label);
        copy.onclick = function () {
          try {
            navigator.clipboard.writeText(step.action.command);
            copy.textContent = "Copied";
            setTimeout(function () { copy.textContent = step.action.label; }, 2000);
          } catch (e) {
            // Clipboard can be refused; the command is on screen either way.
            copy.textContent = "Select it above";
          }
        };
        right.appendChild(copy);
      }
      row.appendChild(right);
      card.appendChild(row);
    });

    return card;
  }

  function render(state) {
    app.textContent = "";

    var head = el("div");
    head.appendChild(el("h1", null, "USAGE Miner"));
    head.appendChild(el("div", "sub", "Version " + state.version));
    app.appendChild(head);

    if (state.pairing) {
      var pair = el("div", "card");
      pair.appendChild(el("h2", null, "Approve this device"));
      pair.appendChild(el("div", "code", state.pairing.userCode));
      pair.appendChild(el("div", "note",
        "Your browser is open at " + state.pairing.verificationUrl.split("?")[0] +
        ". Approve the device there — this window finishes on its own."));
      app.appendChild(pair);
      return;
    }

    if (!state.signedIn) {
      var signIn = el("div", "card");
      signIn.appendChild(el("h2", null, "Get started"));
      signIn.appendChild(el("div", "note",
        "Sign in through your browser. Nothing to copy, and no key to paste."));
      var b = el("button", "primary", "Sign in");
      b.style.marginTop = "12px";
      b.onclick = function () { act(function () { return api("/sign-in", {}); }); };
      signIn.appendChild(b);
      if (state.error) signIn.appendChild(el("div", "err", state.error));
      app.appendChild(signIn);
      // Signed out with it still on: the switch must stay reachable, because
      // turning it off needs no account.
      var outCard = everywhereCard(state);
      if (outCard) app.appendChild(outCard);
      appendFooter(state);
      return;
    }

    // ------------------------------------------------------------ WHO / WHERE
    // The account is a person; this PC is a device. Two lines, never one.
    var acct = el("div", "card");
    if (state.setup && !state.setup.complete) app.appendChild(setupCard(state));

    acct.appendChild(el("h2", null, "Account"));
    var acctRow = el("div", "row");
    acctRow.appendChild(el("div", "name", state.accountDisplay || "USAGE account"));
    acctRow.appendChild(el("span", "tag " + (state.offline ? "off" : "on"), state.offline ? "OFFLINE" : "CONNECTED ✓"));
    acct.appendChild(acctRow);
    var devRow = el("div", "row");
    var devLeft = el("div");
    devLeft.appendChild(el("div", "name", "This PC · " + (state.deviceName || "this device")));
    devLeft.appendChild(el("div", "meta", "Connected to your USAGE account" + (state.networkLabel ? " · " + state.networkLabel : "")));
    devRow.appendChild(devLeft);
    devRow.appendChild(el("span", "tag " + (state.offline ? "off" : "on"), state.offline ? "OFFLINE" : "ONLINE ✓"));
    acct.appendChild(devRow);
    if (state.offline) {
      acct.appendChild(el("div", "err", "Offline — unable to reach USAGE. Mapping status unavailable; local detection still works and usage is kept locally until the connection returns."));
      var again = el("button", "primary", "Retry");
      again.style.marginTop = "8px";
      again.onclick = function () { refresh(); };
      acct.appendChild(again);
    } else if (state.error) acct.appendChild(el("div", "err", state.error));
    if (state.updateAvailable) acct.appendChild(el("div", "note", "A newer USAGE Miner is available."));
    if (state.securityNotice) acct.appendChild(el("div", "note", "Security update: " + state.securityNotice));
    app.appendChild(acct);

    // ------------------------------------------------------------ TODAY
    // Four numbers that are never one number: tracked (this PC reported it),
    // verified (USAGE corroborated it), eligible (policy admitted it), USAGE
    // (what it is estimated to earn). And the reason when the last is zero.
    var anyTracking = state.tools.some(function (t) { return t.mapped && t.tracking && t.tracking.active; });
    var anyMapped = state.tools.some(function (t) { return t.mapped; });
    var pendingBalanceCard = null;
    var today = el("div", "card");
    var todayHead = el("div", "row");
    todayHead.appendChild(el("h2", null, "Today on this PC"));
    todayHead.appendChild(el("span", "tag " + (anyTracking ? "on" : anyMapped ? "warn" : "off"),
      anyTracking ? "TRACKING LIVE" : anyMapped ? "TRACKING READY · IDLE" : "NOT TRACKING"));
    today.appendChild(todayHead);
    if (state.usage) {
      // AI USAGE: input, output, cache read, cache write -- four numbers the
      // server summed, never one number. A request that read 28k tokens from
      // cache is not "20 tokens".
      var tb = state.usage.tracked || { inputTokens: state.usage.trackedTokens, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0, requestCount: 0 };
      today.appendChild(el("div", "meta", "AI usage tracked · " + tb.requestCount + " request" + (tb.requestCount === 1 ? "" : "s") + " · this PC reported"));
      var grid = el("div", "grid");
      var cells = [
        ["Input", fmtTokens(tb.inputTokens), "fresh tokens read"],
        ["Output", fmtTokens(tb.outputTokens), "tokens written" + (tb.reasoningTokens ? " · " + fmtTokens(tb.reasoningTokens) + " reasoning" : "")],
        ["Cache read", fmtTokens(tb.cacheReadTokens), "reused from cache"],
        ["Cache write", fmtTokens(tb.cacheWriteTokens), "stored to cache"]
      ];
      cells.forEach(function (cell) {
        var c = el("div", "cell");
        c.appendChild(el("div", "cell-label", cell[0]));
        c.appendChild(el("div", "cell-value tnum", cell[1]));
        c.appendChild(el("div", "cell-hint", cell[2]));
        grid.appendChild(c);
      });
      today.appendChild(grid);
      var vb = state.usage.verified || { requestCount: 0, cacheReadTokens: 0, cacheWriteTokens: 0 };
      var grid2 = el("div", "grid");
      [
        ["Verified by USAGE", vb.requestCount + " req · " + fmtTokens(state.usage.verifiedTokens) + " fresh", "trusted records only"],
        ["Eligible", fmtMicros(state.usage.eligibleComputeMicros), "allowed to earn · versioned pricing, not token counts"],
        ["USAGE today", state.usage.estimatedPoints ? "~" + fmtPoints(state.usage.estimatedPoints) : "—", "estimate · credited when the day settles, just after midnight UTC"]
      ].forEach(function (cell) {
        var c = el("div", "cell");
        c.appendChild(el("div", "cell-label", cell[0]));
        c.appendChild(el("div", "cell-value tnum", cell[1]));
        c.appendChild(el("div", "cell-hint", cell[2]));
        grid2.appendChild(c);
      });
      today.appendChild(grid2);
      // The day resets at midnight UTC, so the morning's panel is empty by design.
      // Say where the rest of the account is rather than leave a person guessing.
      today.appendChild(el("div", "note",
        "This panel counts AI apps on this PC for today (UTC) only. Chat on the USAGE website counts too, on your dashboard."));
      if (typeof state.usage.balancePoints === "number") {
        var bal = el("div", "card");
        var balHead = el("div", "row");
        balHead.appendChild(el("h2", null, "USAGE Points"));
        balHead.appendChild(el("span", "cell-value tnum", fmtPoints(state.usage.balancePoints)));
        bal.appendChild(balHead);
        var lc = state.usage.lastCredit;
        bal.appendChild(el("div", "note", lc
          ? "Last settled day " + lc.day + ": +" + fmtPoints(lc.points) + ". Points stay on your account; they cannot be sent, sold or exchanged."
          : "Nothing settled yet. Points are credited the morning after a day you mine."));
        pendingBalanceCard = bal;
      }
      if (state.usage.recent && state.usage.recent.length) {
        var feed = el("div", "feed");
        state.usage.recent.slice(0, 6).forEach(function (r) {
          var line = el("div", "row");
          var b = r.breakdown;
          var detail = b
            ? fmtTokens(b.inputTokens) + " in · " + fmtTokens(b.outputTokens) + " out" +
              (b.cacheReadTokens ? " · " + fmtTokens(b.cacheReadTokens) + " cache read" : "") +
              (b.cacheWriteTokens ? " · " + fmtTokens(b.cacheWriteTokens) + " cache write" : "") +
              (b.reasoningTokens ? " · " + fmtTokens(b.reasoningTokens) + " reasoning" : "")
            : fmtTokens(r.tokens) + " fresh tokens";
          line.appendChild(el("span", "meta", toolName(state, r.tool) + (r.model ? " · " + r.model : "") + " · " + detail + " · " + fmtTime(r.at)));
          line.appendChild(el("span", "tag " + (r.status === "tracked" ? "off" : "on"),
            r.status === "tracked" ? "TRACKED" : r.status === "routed" ? "ROUTED ✓" : "VERIFIED ✓"));
          feed.appendChild(line);
        });
        today.appendChild(feed);
      }
    } else if (state.offline) {
      today.appendChild(el("div", "empty", "Today's figures need USAGE. They appear when the connection returns."));
    } else {
      today.appendChild(el("div", "empty", "Figures appear once USAGE has seen usage from this PC."));
    }
    if (state.whyNotEarning) {
      var why = el("div", "note");
      why.appendChild(el("strong", null, "Why no USAGE? "));
      why.appendChild(document.createTextNode(state.whyNotEarning));
      today.appendChild(why);
    }
    app.appendChild(today);
    if (pendingBalanceCard) app.appendChild(pendingBalanceCard);

    // ------------------------------------------------------------ AI ROUTE
    // What actually carries Claude Code's requests when started from here.
    // Two states, never blurred: a verified route on the user's own connected
    // provider, or no route at all -- Claude Code on its own sign-in, tracked
    // locally. There is no USAGE gateway fallback.
    var routeCard = el("div", "card");
    routeCard.appendChild(el("h2", null, "AI route"));
    if (state.route && state.route.kind === "provider") {
      var rRow = el("div", "row");
      var rLeft = el("div");
      rLeft.appendChild(el("div", "name", state.route.label));
      rLeft.appendChild(el("div", "meta", "Your connected provider" + (state.route.claudeCompatible ? " · Claude Code compatible" : "") + " · verified routing"));
      if (state.route.wire) rLeft.appendChild(el("div", "meta", "Wire: " + state.route.wire + (state.route.auth ? " · Auth: " + state.route.auth : "")));
      rLeft.appendChild(el("div", "meta", "Reward: " + state.route.rewardStatus.toUpperCase() + " — " + state.route.reason));
      rRow.appendChild(rLeft);
      rRow.appendChild(el("span", "tag " + (state.route.rewardStatus === "eligible" ? "on" : "warn"), state.route.rewardStatus.toUpperCase()));
      routeCard.appendChild(rRow);
    } else {
      routeCard.appendChild(el("div", "empty", "No verified AI route. " + (state.route && state.route.reason ? state.route.reason : "Claude Code runs on its own sign-in (Track only), which does not earn.")));
    }
    if (!state.route || state.route.kind !== "provider") {
      var connect = el("button", "primary", "Connect your provider");
      connect.style.marginTop = "10px";
      connect.onclick = function () { act(function () { return api("/open", { target: "providers" }); }); };
      routeCard.appendChild(connect);
    }
    app.appendChild(routeCard);

    // --------------------------------------------------------- AI APPS
    // One row per app, answering one question: what is happening right now?
    // Every word comes from the row the local process built (tool-row.ts);
    // the page lays it out and adds nothing. Local-only telemetry is TRACKING,
    // never mining.
    var tools = el("div", "card");
    tools.appendChild(el("h2", null, "AI apps on this PC"));
    state.tools.forEach(function (t) {
      var r = t.row;
      var row = el("div", "tool");
      var head = el("div", "row");
      head.appendChild(el("div", "name", (r ? r.title : t.name) + (t.version ? "  " + t.version : "") + (t.experimental ? "  (experimental)" : "")));
      if (r && r.tracking === "ACTIVE") head.appendChild(el("span", "tag on", "TRACKING LIVE"));
      else head.appendChild(el("span", "tag off", r && r.detected === "YES" ? "NOT TRACKING" : "—"));
      row.appendChild(head);

      var kv = el("div", "kv");
      function line(label, value, cls) {
        kv.appendChild(el("div", "k", label));
        kv.appendChild(el("div", "v" + (cls ? " " + cls : ""), value));
      }
      line("Detected", r ? r.detected : (t.installed ? "YES" : "NO"));
      if (t.installed && !t.meterable) {
        line("Usage tracking", "UNAVAILABLE");
        row.appendChild(kv);
        row.appendChild(el("div", "note", t.availabilityNote || "This app cannot be measured here."));
      } else if (r && t.installed) {
        line("Usage tracking", r.tracking + (r.trackingVia ? " · " + r.trackingVia : ""));
        if (r.mode === "verified_route") line("Route", r.route || "—");
        else line("Usage source", r.usageSource || "Your own sign-in");
        line("Verification", r.verification);
        line("Reward", r.reward);
        var d = r.today;
        var today = "Input " + fmtMaybe(d.input) + " · Output " + fmtMaybe(d.output) +
          " · Cache read " + fmtMaybe(d.cacheRead) + " · Cache write " + fmtMaybe(d.cacheWrite) +
          (d.reasoning !== null ? " · Reasoning " + fmtMaybe(d.reasoning) : "");
        line("Today", today, "tnum");
        r.coverage.forEach(function (c) {
          line(c.mode, c.label + (c.limitation ? " — " + c.limitation : ""), c.level === "usage_detail" ? "" : "dim");
        });
        var tr = t.tracking || {};
        if (tr.lastSyncOutcome) {
          var ok = tr.lastSyncOutcome === "accepted" || tr.lastSyncOutcome === "duplicate";
          line("Last sync", (tr.lastSyncAt ? fmtTime(tr.lastSyncAt) + " · " : "") + (tr.lastSyncLabel || tr.lastSyncOutcome) + (tr.buffered ? " · " + tr.buffered + " waiting" : ""), ok ? "" : "bad");
        }
        row.appendChild(kv);
        if (!d.available && state.usage) row.appendChild(el("div", "note", "Per-app figures for today are not provided by this USAGE server yet; the totals above include this app."));
        if (r.mode === "track_only" && t.launch && t.launch.explanation) row.appendChild(el("div", "note", t.launch.explanation));
      } else {
        row.appendChild(kv);
      }
      if (t.detectionUnavailable) row.appendChild(el("div", "meta", "Detection unavailable — checked again on the next refresh."));
      if (t.conflict) row.appendChild(el("div", "meta", t.conflict));

      var actions = el("div", "actions");
      actions.style.marginTop = "8px";
      if (r && r.actions.startVerifiedRoute.visible) {
        var start = el("button", "primary", "Start verified route");
        start.disabled = !r.actions.startVerifiedRoute.enabled;
        start.title = r.actions.startVerifiedRoute.reason || "Starts the app through a verified USAGE route on your connected provider.";
        start.onclick = function () {
          act(function () {
            return api("/launch", { tool: t.id }).then(function (res) {
              if (res && res.error) { window.alert(res.message || "Could not start it."); return; }
              if (res && res.label) {
                var was = start.textContent;
                start.textContent = (res.mode === "track_only" ? "Tracking: " : "Starting: ") + res.label + " · " + String(res.reward || "") + (res.wire ? " · " + res.wire : "");
                setTimeout(function () { start.textContent = was; }, 6000);
              }
            });
          });
        };
        actions.appendChild(start);
      }
      if (r && r.actions.trackOnly.visible) {
        var track = el("button", r.actions.startVerifiedRoute.visible ? null : "primary", "Track only");
        track.disabled = !r.actions.trackOnly.enabled;
        track.title = r.actions.trackOnly.reason || "Starts the app on its own sign-in and provider; USAGE only tracks usage on this PC. Does not earn.";
        track.onclick = function () {
          if (t.mappingStatus !== "on" && !window.confirm(
            "Track " + t.name + " on this PC?\\n\\nUSAGE reads: " + t.reads.join(", ") +
            ".\\nUSAGE never reads: " + t.neverReads.join(", ") + "."
          )) return;
          act(function () {
            var ready = t.mappingStatus === "on" ? Promise.resolve({}) : api("/mapping", { tool: t.id, enabled: true });
            return ready.then(function (m) {
              if (m && m.error) { window.alert(m.message || "Could not turn tracking on."); return; }
              return api("/launch", { tool: t.id, route: false }).then(function (res) {
                if (res && res.error) window.alert(res.message || "Could not start it.");
              });
            });
          });
        };
        actions.appendChild(track);
      }
      if (r && r.actions.stopTracking.visible) {
        var stop = el("button", null, "Stop tracking");
        stop.disabled = !r.actions.stopTracking.enabled;
        stop.title = r.actions.stopTracking.reason || "USAGE stops accepting this app's usage from this PC.";
        stop.onclick = function () {
          if (!window.confirm("Stop tracking " + t.name + " on this PC?\\n\\nThe app keeps running; USAGE stops accepting its usage.")) return;
          act(function () {
            return api("/tracking/stop", { tool: t.id }).then(function (res) {
              if (res && res.error) window.alert(res.message || "Could not stop tracking.");
            });
          });
        };
        actions.appendChild(stop);
      }
      row.appendChild(actions);
      tools.appendChild(row);
    });
    tools.appendChild(el("div", "note",
      "\\"Start verified route\\" sends the app's requests through a verified USAGE route on your connected provider and can earn. " +
      "\\"Track only\\" keeps the app on its own sign-in and provider: USAGE measures token counts from the app's own telemetry on this PC, and that does not earn. " +
      "Nothing is written to the app's settings and nothing is read from your files."));
    app.appendChild(tools);

    // ------------------------------------------------------------ CLAUDE CODE EVERYWHERE
    var everywhere = everywhereCard(state);
    if (everywhere) app.appendChild(everywhere);

    // ------------------------------------------------------------ PRIVACY
    var privacy = el("div", "card");
    privacy.appendChild(el("h2", null, "Exactly what USAGE reads"));
    state.tools.filter(function (t) { return t.installed && t.meterable; }).forEach(function (t) {
      var block = el("div", "priv");
      block.appendChild(el("div", "name", t.name));
      block.appendChild(el("div", "meta", "Reads: " + (t.reads.length ? t.reads.join(" · ") : "nothing")));
      block.appendChild(el("div", "meta", "Never reads: " + t.neverReads.join(" · ")));
      privacy.appendChild(block);
    });
    privacy.appendChild(el("div", "note",
      "USAGE measures compute metadata, not conversations. No prompt, response, file, command or line of code leaves this computer through USAGE Miner — the parser has no field to put one in."));
    app.appendChild(privacy);

    appendFooter(state);
  }

  // Claude Code started from a terminal or VS Code, not from this window.
  // Opt-in, because it writes into Claude Code's own settings file.
  //
  // Shown whenever it is ON, whatever else is true -- signed out, revoked,
  // Claude Code detection timed out on this poll: a switch that is on must
  // never vanish from under the person trying to turn it off.
  function everywhereCard(state) {
    var ao = state.alwaysOn;
    if (!ao) return null;
    var claudeTool = state.tools.filter(function (t) { return t.id === "claude-code"; })[0];
    var offerable = state.signedIn && claudeTool && claudeTool.installed;
    if (!ao.enabled && !offerable && !aoNotice) return null;

    var card = el("div", "card");
    var head = el("div", "row");
    head.appendChild(el("h2", null, "Measure Claude Code everywhere"));
    var tag = !ao.enabled ? ["off", "OFF"]
      : ao.listening === "listening" ? ["on", "ON"]
      : ao.listening === "port_in_use" ? ["warn", "ON · RECEIVED BY ANOTHER WINDOW OR PROGRAM"]
      : ["warn", "ON · STARTING"];
    head.appendChild(el("span", "tag " + tag[0], tag[1]));
    card.appendChild(head);

    if (aoNotice) {
      var box = el("div", aoNotice.kind === "err" ? "err" : "note");
      box.appendChild(el("strong", null, aoNotice.title));
      box.appendChild(el("div", null, aoNotice.text));
      if (aoNotice.warning) box.appendChild(el("div", "err", aoNotice.warning));
      card.appendChild(box);
    }

    card.appendChild(el("div", "note",
      "Counts Claude Code however you start it: a terminal, a shortcut or the VS Code extension, " +
      "while USAGE Miner is running. It adds telemetry settings to Claude Code's settings.json: " +
      "no password, no key, and prompts and replies stay switched off. Turning it off removes exactly those settings."));
    card.appendChild(el("div", "note",
      "This measures usage; it does not earn. Earning still needs Start with USAGE, because only a request " +
      "USAGE routes can be verified."));
    if (ao.enabled && ao.listening === "port_in_use") {
      card.appendChild(el("div", "meta",
        "Port 47823 is held by another USAGE Miner window or another program. If it is another USAGE Miner window, that window receives instead; if not, nothing is received. Turning this off stops it in every USAGE Miner window."));
    }
    if (ao.enabled && ao.eventsSinceStart > 0) {
      card.appendChild(el("div", "meta",
        ao.eventsSinceStart + " Claude Code request" + (ao.eventsSinceStart === 1 ? "" : "s") + " measured since the miner started" +
        (ao.lastEventAt ? " · last " + fmtTime(ao.lastEventAt) : "")));
    }

    var want = !ao.enabled;
    if (!want || offerable) {
      var button = el("button", want ? "primary" : "", want ? "Turn on" : "Turn off");
      button.style.marginTop = "10px";
      button.disabled = busy;
      button.onclick = function () {
        var started = act(function () {
          aoNotice = null;
          return api("/always-on", { enabled: want }).then(function (r) {
            if (!r || r.error || r.ok !== true) {
              aoNotice = { kind: "err", title: want ? "COULD NOT TURN MEASURE EVERYWHERE ON" : "COULD NOT TURN MEASURE EVERYWHERE OFF", text: describeFailure(r) };
              return;
            }
            aoNotice = { kind: "ok", title: r.title, text: r.message, warning: r.warning || null };
          }, function (error) {
            aoNotice = {
              kind: "err",
              title: want ? "COULD NOT TURN MEASURE EVERYWHERE ON" : "COULD NOT TURN MEASURE EVERYWHERE OFF",
              text: "USAGE Miner did not answer (" + categorize(error) + "). Nothing may have changed. If this keeps happening, close this tab and open USAGE Miner again."
            };
          });
        });
        if (started) {
          button.disabled = true;
          button.textContent = want ? "Turning on…" : "Turning off…";
        }
      };
      card.appendChild(button);
    }
    return card;
  }

  function describeFailure(r) {
    if (!r) return "USAGE Miner gave no answer. Nothing may have changed.";
    var status = r.httpStatus;
    if (status === 403) return r.message || "This window is no longer connected to the USAGE Miner that opened it. Close this tab and open USAGE Miner again.";
    var text = r.message || ("USAGE Miner refused the request (" + (r.error || "error") + ").");
    return status ? text + " [" + status + "]" : text;
  }

  function fmtTokens(n) {
    n = Number(n || 0);
    if (n >= 1e6) return (n / 1e6).toFixed(n >= 1e7 ? 0 : 1) + "M";
    if (n >= 1e3) return (n / 1e3).toFixed(n >= 1e4 ? 0 : 1) + "k";
    return String(n);
  }
  function fmtMaybe(n) {
    return n === null || n === undefined ? "—" : fmtTokens(n);
  }
  function fmtTime(iso) {
    try {
      var d = new Date(iso);
      if (isNaN(d.getTime())) return "";
      return d.getHours() + ":" + (d.getMinutes() < 10 ? "0" : "") + d.getMinutes();
    } catch (e) { return ""; }
  }
  function fmtPoints(n) {
    var v = Number(n);
    return isFinite(v) ? Math.round(v).toLocaleString("en-US") : "—";
  }

  function fmtMicros(m) {
    m = Number(m || 0);
    return "$" + (m / 1e6).toFixed(m >= 1e6 ? 2 : 4) + " equiv.";
  }
  function toolName(state, id) {
    var t = state.tools.filter(function (x) { return x.id === id; })[0];
    return t ? t.name : id;
  }
  function ceilingLabel(c) {
    return c === "routed_confirmed" ? "routed" : c === "provider_correlated" ? "verified (when correlated)" : "tracked only";
  }

  function appendFooter(state) {
    var links = el("div", "links");
    if (state.signedIn) {
      var dash = el("button", null, "Open dashboard");
      dash.onclick = function () { act(function () { return api("/open", { target: "dashboard" }); }); };
      links.appendChild(dash);

      var devices = el("button", null, "Manage devices");
      devices.onclick = function () { act(function () { return api("/open", { target: "miners" }); }); };
      links.appendChild(devices);

      var so = el("button", null, "Sign out");
      so.onclick = function () {
        if (!window.confirm("Sign this device out? Mining and tracking stop until you sign in again.")) return;
        act(function () { return api("/sign-out", {}); });
      };
      links.appendChild(so);
    }
    // From this process only: the build that is running, the protocol it
    // speaks, and how it was started. Never the server's idea of either.
    var dg = state.diagnostics;
    var dgText = dg
      ? "Miner " + dg.version + " · protocol " + dg.protocol + " · launch: " + dg.launch
      : "Miner " + state.version;
    app.appendChild(el("div", "meta", "Diagnostics: " + dgText +
      (state.signedIn ? " · device " + (state.deviceId || "—") + " · network " + (state.network || "—") : "")));
    var quit = el("button", null, "Quit");
    quit.onclick = function () {
      api("/quit", {});
      document.body.textContent = "You can close this tab.";
    };
    links.appendChild(quit);
    app.appendChild(links);
  }

  function refresh() {
    return api("/state").then(function (state) {
      if (!state || typeof state !== "object" || !Array.isArray(state.tools)) throw new Error("bad_json");
      render(state);
      rendered = true;
    }).catch(function (error) {
      if (rendered && categorize(error) === "unreachable") {
        app.textContent = "";
        app.appendChild(el("p", "err", "USAGE Miner is no longer running. You can close this tab."));
        return;
      }
      renderFailure(categorize(error));
    });
  }

  // Startup timeout: if nothing has rendered by now, something is wrong and
  // the user is told so. There is no state in which "Loading…" stays forever.
  var STARTUP_TIMEOUT_MS = 25000;
  setTimeout(function () { if (!rendered && app.textContent.indexOf("Loading") !== -1) renderFailure("startup_timeout"); }, STARTUP_TIMEOUT_MS);

  try { refresh(); } catch (error) { renderFailure("render"); }
  // Slow enough to be invisible, fast enough that an approval in the browser
  // lands in this window without the user doing anything.
  setInterval(function () { if (!busy && !pointerDown) refresh(); }, 3000);
})();
</script>
</body>
</html>`;
}
