/**
 * The desktop window's markup.
 *
 * One self-contained string: no bundler step, no asset paths, no network. The
 * page is served once from loopback and never fetches anything external, so
 * there is nothing here for a CDN or an ad blocker to interfere with, and no
 * third party learns that the miner is running.
 *
 * The nonce is interpolated into a JS string literal. It is generated by
 * `randomBytes(...).toString("base64url")`, so it is [A-Za-z0-9_-] only and
 * cannot terminate the literal -- but the assertion is enforced here rather
 * than assumed, because "the caller always passes something safe" is how
 * injection bugs are written.
 */

const SAFE_NONCE = /^[A-Za-z0-9_-]+$/;

export function renderApp(nonce: string): string {
  if (!SAFE_NONCE.test(nonce)) throw new Error("renderApp: unsafe nonce");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'">
<title>USAGE Miner</title>
<style>
  :root {
    color-scheme: light dark;
    --bg: #fbfbfa; --surface: #ffffff; --border: #e6e4df; --text: #17150f;
    --muted: #6b665c; --verified: #1f7a4d; --routed: #2563a8; --reported: #8b8578;
    --danger: #a33; --accent: #17150f; --accent-text: #fbfbfa;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #131210; --surface: #1b1a17; --border: #2e2c27; --text: #efece5;
      --muted: #9a948a; --verified: #4ec38a; --routed: #6aa6e8; --reported: #8b8578;
      --accent: #efece5; --accent-text: #131210;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--bg); color: var(--text);
    font: 14px/1.5 ui-sans-serif, system-ui, "Segoe UI", sans-serif;
  }
  .wrap { max-width: 620px; margin: 0 auto; padding: 32px 20px 56px; }
  h1 { font-size: 22px; font-weight: 500; letter-spacing: -0.01em; margin: 0; }
  .sub { color: var(--muted); font-size: 12px; margin-top: 4px; }
  .card {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 6px; padding: 16px; margin-top: 12px;
  }
  .card h2 {
    font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em;
    color: var(--muted); font-weight: 500; margin: 0 0 10px;
  }
  .row { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 8px 0; }
  .row + .row { border-top: 1px solid var(--border); }
  .name { font-weight: 500; }
  .meta { color: var(--muted); font-size: 12px; }
  button {
    font: inherit; font-size: 13px; padding: 6px 14px; border-radius: 5px;
    border: 1px solid var(--border); background: var(--surface); color: var(--text);
    cursor: pointer;
  }
  button:hover:not(:disabled) { border-color: var(--muted); }
  button:disabled { opacity: 0.45; cursor: default; }
  button.primary { background: var(--accent); color: var(--accent-text); border-color: var(--accent); }
  .tag { font-size: 11px; padding: 2px 7px; border-radius: 999px; border: 1px solid currentColor; }
  .tag.on { color: var(--verified); }
  .tag.off { color: var(--reported); }
  .tag.warn { color: var(--routed); }
  .code {
    font: 600 28px/1 ui-monospace, "Cascadia Mono", Consolas, monospace;
    letter-spacing: 0.22em; padding: 14px 0 6px;
  }
  .note { color: var(--muted); font-size: 12px; margin-top: 10px; }
  .err { color: var(--danger); font-size: 12px; margin-top: 10px; }
  .links { margin-top: 20px; display: flex; gap: 16px; flex-wrap: wrap; }
  .links button { border: 0; background: none; padding: 0; color: var(--routed); font-size: 12px; }
  .empty { color: var(--muted); font-size: 12px; }
</style>
</head>
<body>
<div class="wrap" id="app"><p class="empty">Loading…</p></div>
<script>
(function () {
  "use strict";
  var K = "${nonce}";
  var app = document.getElementById("app");
  var busy = false;

  function api(path, body) {
    return fetch(path + "?k=" + K, {
      method: body === undefined ? "GET" : "POST",
      headers: { "content-type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body)
    }).then(function (r) { return r.json(); });
  }

  // Everything shown comes from the local process, but it is still built with
  // textContent rather than innerHTML: a provider label or a device name is
  // data, and data never becomes markup.
  function el(tag, cls, text) {
    var node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text !== undefined && text !== null) node.textContent = String(text);
    return node;
  }

  function act(fn) {
    if (busy) return;
    busy = true;
    fn().catch(function () {}).then(function () { busy = false; refresh(); });
  }

  function render(state) {
    app.textContent = "";

    var head = el("div");
    head.appendChild(el("h1", null, "USAGE Miner"));
    head.appendChild(el("div", "sub", "Version " + state.version +
      (state.deviceName ? " · " + state.deviceName : "")));
    app.appendChild(head);

    if (state.pairing) {
      var pair = el("div", "card");
      pair.appendChild(el("h2", null, "Approve this device"));
      pair.appendChild(el("div", "code", state.pairing.userCode));
      pair.appendChild(el("div", "note",
        "Your browser is open at " + state.pairing.verificationUrl.split("?")[0] +
        ". Approve the device there — this window finishes on its own."));
      app.appendChild(pair);
      return;
    }

    if (!state.signedIn) {
      var signIn = el("div", "card");
      signIn.appendChild(el("h2", null, "Get started"));
      signIn.appendChild(el("div", "note",
        "Sign in through your browser. Nothing to copy, and no key to paste."));
      var b = el("button", "primary", "Sign in");
      b.style.marginTop = "12px";
      b.onclick = function () { act(function () { return api("/sign-in", {}); }); };
      signIn.appendChild(b);
      if (state.error) signIn.appendChild(el("div", "err", state.error));
      app.appendChild(signIn);
      appendFooter(state);
      return;
    }

    var acct = el("div", "card");
    acct.appendChild(el("h2", null, "Account"));
    var acctRow = el("div", "row");
    acctRow.appendChild(el("div", "name", state.accountLabel || "Signed in"));
    acctRow.appendChild(el("span", "meta", state.network || ""));
    acct.appendChild(acctRow);
    if (state.error) acct.appendChild(el("div", "err", state.error));
    if (state.updateAvailable) {
      acct.appendChild(el("div", "note", "A newer USAGE Miner is available."));
    }
    if (state.securityNotice) {
      acct.appendChild(el("div", "note", "Security update: " + state.securityNotice));
    }
    app.appendChild(acct);

    var prov = el("div", "card");
    prov.appendChild(el("h2", null, "Providers"));
    if (!state.providers.length) {
      prov.appendChild(el("div", "empty", "No AI provider connected yet."));
      var connect = el("button", "primary", "Connect a provider");
      connect.style.marginTop = "12px";
      connect.onclick = function () { act(function () { return api("/open", { target: "providers" }); }); };
      prov.appendChild(connect);
    } else {
      state.providers.forEach(function (p) {
        var row = el("div", "row");
        row.appendChild(el("div", "name", p.label));
        row.appendChild(el("span", "meta", p.miningLabel));
        prov.appendChild(row);
      });
    }
    app.appendChild(prov);

    var tools = el("div", "card");
    tools.appendChild(el("h2", null, "AI tools on this computer"));
    state.tools.forEach(function (t) {
      var row = el("div", "row");
      var left = el("div");
      var title = el("div", "name", t.name + (t.experimental ? "  (experimental)" : ""));
      left.appendChild(title);
      left.appendChild(el("div", "meta",
        !t.installed ? "Not installed"
          : t.conflict ? t.conflict
          : t.mining ? "Mining through USAGE"
          : t.mode === "launch"
            ? "Started by USAGE — nothing is written to disk"
            : "Installed" + (t.version ? " · " + t.version : "")));
      row.appendChild(left);

      var right = el("div");
      if (!t.installed) {
        right.appendChild(el("span", "tag off", "—"));
      } else if (t.mode === "launch") {
        // No enable button at all for a tool USAGE starts itself. There is
        // nothing to turn on: routing exists for the life of the session.
        var start = el("button", "primary", "Start with USAGE");
        start.onclick = function () {
          act(function () {
            return api("/launch", { tool: t.id }).then(function (r) {
              if (r && r.error) window.alert(r.message || "Could not start it.");
            });
          });
        };
        right.appendChild(start);
      } else if (t.mining) {
        var off = el("button", null, "Turn off");
        off.onclick = function () { act(function () { return api("/disable", { tool: t.id }); }); };
        right.appendChild(off);
      } else {
        var on = el("button", "primary", t.conflict ? "Replace" : "Enable mining");
        on.onclick = function () {
          if (t.conflict && !window.confirm(
            t.name + " already points at a custom endpoint.\\n\\n" + t.conflict +
            "\\n\\nReplace it? Your current settings are backed up and restored when you turn mining off."
          )) return;
          act(function () {
            return api("/enable", { tool: t.id, force: Boolean(t.conflict) }).then(function (r) {
              if (r && r.error) window.alert(r.message || "Could not enable mining.");
              else if (r && r.ok === false) window.alert(r.message);
            });
          });
        };
        right.appendChild(on);
      }
      row.appendChild(right);
      tools.appendChild(row);
    });
    tools.appendChild(el("div", "note",
      "Tools USAGE starts get their routing in that session's environment — no credential is written to disk, and it is gone when the tool closes. Tools that are configured have their own config file edited, which can name the credential but never contains it; what was there is backed up, and turning mining off puts it back exactly."));
    app.appendChild(tools);

    appendFooter(state);
  }

  function appendFooter(state) {
    var privacy = el("div", "card");
    privacy.appendChild(el("h2", null, "What USAGE records"));
    privacy.appendChild(el("div", "note",
      "Model, token counts, cost, latency and timing. Never your prompts, your responses, your tool arguments or your code."));
    app.appendChild(privacy);

    var links = el("div", "links");
    if (state.signedIn) {
      var dash = el("button", null, "Open dashboard");
      dash.onclick = function () { act(function () { return api("/open", { target: "dashboard" }); }); };
      links.appendChild(dash);

      var devices = el("button", null, "Manage devices");
      devices.onclick = function () { act(function () { return api("/open", { target: "miners" }); }); };
      links.appendChild(devices);

      var so = el("button", null, "Sign out");
      so.onclick = function () {
        if (!window.confirm("Sign this device out? Mining stops until you sign in again.")) return;
        act(function () { return api("/sign-out", {}); });
      };
      links.appendChild(so);
    }
    var quit = el("button", null, "Quit");
    quit.onclick = function () {
      api("/quit", {});
      document.body.textContent = "You can close this tab.";
    };
    links.appendChild(quit);
    app.appendChild(links);
  }

  function refresh() {
    return api("/state").then(render).catch(function () {
      app.textContent = "";
      app.appendChild(el("p", "err", "USAGE Miner is no longer running. You can close this tab."));
    });
  }

  refresh();
  // Slow enough to be invisible, fast enough that an approval in the browser
  // lands in this window without the user doing anything.
  setInterval(function () { if (!busy) refresh(); }, 3000);
})();
</script>
</body>
</html>`;
}
